name: Get JSON

on:
#   schedule:
#     - cron: '*/5 * * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get JSON
        run: |
          curl -s "https://123milhas.com/api/v3/top-ofertas-com-ap/continent/europa?between-end=15&between-start=1&duration=1&origin=recife&page=1" > data.json
        shell: bash
      
      - name: EDIT JSON
        run: |
          jq ".topOffers[] | {
                    outbound_airline_name,
                    inbound_airline_name,
                    departure_time,
                    departure_date,
                    outbound_arrival_time,
                    return_time,
                    return_date,
                    return_arrival_time,
                    duration,
                    our_price,
                    airline_price,
                    escales,
                    connections,
                    best_price,
                    origin_name,
                    destination_name,
                    airport_destination_name,
                    airport_origin_name,
                    url_search}" data.json | jq -n [inputs] >> data.json       
        shell: bash
     
      - name: SAVE CSV
        run: |
          cat data.json | jq -r '.[] | join(";")' >  dados/$(date +"%Y_%m_%d_%I_%M_%p").csv
        shell: bash
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update data.json"
          commit_author: "GitHub Actions <actions@github.com>"
          file_pattern: "dados/*.csv"
